ignore:
  - "**/python"
  - "test/**/*"
  - "src/mqt/qecc/cc_decoder/plots.py"
  - "src/mqt/qecc/analog_information_decoding/utils/data_utils.py"
  - "src/mqt/qecc/analog_information_decoding/code_construction/*"

coverage:
  range: 60..90
  precision: 1
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.5%
        removed_code_behavior: adjust_base
      - type: patch
        target: 90%
        threshold: 1%
  individual_flags:
    - name: cpp
      paths:
        - "include"
        - "src"
    - name: python
      paths:
        - "src/mqt/**/*.py"
      statuses:
        - type: project
          threshold: 0.5%
          removed_code_behavior: adjust_base
        - type: patch
          target: 95%
          threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
  show_carryforward_flags: true
